[devshell]
packages = [
  "alejandra",
  "bacon",
  "cargo-nextest",
  "deadnix",
  "miniserve",
  "tombi",
  "treefmt"
]
motd = """
{202}ðŸ”¨ Welcome to devshell{reset}
$(type -p menu &>/dev/null && menu)

Check out ðŸ¥“ "bacon --list-jobs" for watch ðŸ‘€ commands e.g.
    bacon shell-hook -- nushell
"""

[[commands]]
name = "fix"
category = "linting"
help = "Fix clippy, format Rust, TOML, Nix files"
command = "treefmt"

[[commands]]
name = "lint"
category = "linting"
help = "Lint project"
command = "nix flake check"

[[commands]]
name = "check"
category = "linting"
help = "Simple 'does it compile' check"
command = "cargo check"
